[package]
name = "prompt_testing_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
llm = { version = "1.0.4", features = ["openai", "anthropic", "ollama", "deepseek", "xai", "phind", "google", "groq"] }
tokio = { version = "1.45.0", features = ["full"] }

